{{ link_to("/admin/cities/new", t._('new'), "class": "btn btn-primary") }}

{{ form("admin/cities", "class": "form-inline pull-right") }}
    <div class="form-group">
        {{ text_field("name", "class": "form-control", "placeholder": t._('name') ) }}
    </div>

    {{ submit_button("Search", "class": "btn btn-default") }}
{{ endForm() }}

<p>{{ this.flashSession.output() }}</p>

<div class="box">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ t._('name') }}</th>
                <th>{{ t._('latitude') }}</th>
                <th>{{ t._('longitude') }}</th>
                <th>{{ t._('status') }}</th>
                <th class="text-right">{{ t._('actions') }}</th>
            </tr>
        </thead>
        <tbody>
        {% if page.items %}
            {% for item in page.items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name|e }}</td>
                    <td>{{ item.latitude|e }}</td>
                    <td>{{ item.longitude|e }}</td>
                    <td>{{ t._(item.active ? 'active' : 'inactive') }}</td>
                    <td class="text-right">
                        {{ link_to("/admin/cities/edit/" ~ item.id, t._('edit')) }}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="6" class="warning text-center">{{ t._('no_data') }}</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
</div>

{% if page.total_pages > 1 %}
    <ul class="pagination">
        {% if page.current > 1 %}
            <li>{{ link_to("/admin/cities", t._('first')) }}</li>
            <li>{{ link_to("/admin/cities?page=" ~ page.before, t._('previous')) }}</li>
        {% else %}
            <li class="disabled"><span>{{ t._('first') }}</span></li>
            <li class="disabled"><span>{{ t._('previous') }}</span></li>
        {% endif %}

        {% for i in 1..page.total_pages %}
            {% if i == page.current %}
                <li class="active"><span>{{ i }}</span></li>
            {% else %}
                <li>{{ link_to("/admin/cities?page=" ~ i, i) }}</li>
            {% endif %}
        {% endfor %}


        {% if page.current < page.total_pages %}
            <li>{{ link_to("/admin/cities?page=" ~ page.next, t._('next')) }}</li>
            <li>{{ link_to("/admin/cities?page=" ~ page.last, t._('last')) }}</li>
        {% else %}
            <li class="disabled"><span>{{ t._('next') }}</span></li>
            <li class="disabled"><span>{{ t._('last') }}</span></li>
        {% endif %}
    </ul>
{% endif %}